apiVersion: v1
kind: Service
metadata:
  name: nginx-statefulsets
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web-statefulsets
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-statefulsets
spec:
  serviceName: "nginx-statefulsets"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web-statefulsets
        volumeMounts:
        - name: www-statefulsets
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
